baseurl = "/"
languageCode = "en-us"
title = "wangonya's blog"
theme = "hugo-xmin"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/blog/:slug/"


[params]
    description = "wangonya's blog"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokailight"
    tabWidth = 4