title = "Kelvin Wangonya"
base_url = "https://wangonya.com"
compile_sass = true
build_search_index = false
default_language = "en"
minify_html = true
taxonomies = [{name = "tags"}]

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "classic-modified"

[extra]
meta = "Wangonya's website. | Software engineer. Mostly backend related stuff with Python."
about = "Software engineer. Mostly backend stuff with Python."
links = [
    { title = "Now", href = "/now" },
    { title = "GitHub", href = "https://github.com/wangonya" },
    { title = "LinkedIn", href = "https://linkedin.com/in/wangonya/" },
    { title = "Email", href = "mailto:kwangonya@gmail.com" },
]

