baseurl = "https://wangonya.com/"
title = "Kinyanjui Wangonya"
description = "Kinyanjui Wangonya's website and blog."
author = "Kinyanjui Wangonya"
enableRobotsTXT = true
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
googleAnalytics = "UA-145132150-1"

pygmentsstyle       = "perldoc"
pygmentscodefences  = true

[params]
sitename = "Kinyanjui Wangonya"
disableWebFonts = false

[[menu.main]]
name = "Blog"
url  = "/blog"
