baseurl = "https://wangonya.com"
languageCode = "en-us"
title = "Kelvin Wangonya"
theme = "wangonya"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
pluralizeListTitles = false

[permalinks]
    posts = "blog/:slug/"

[params]
    email = "kwangonya@gmail.com"
    about = "Software engineer. Mostly backend work with Python."
    meta = "Wangonya's blog. | Software engineer. Mostly backend work with Python."
    author = "Kelvin Wangonya"

# Header
[menu]
  [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
  [[menu.main]]
        identifier = "now"
        name = "Now"
        url = "/now"

[[params.links]]
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/wangonya"
    [[params.links.link]]
      name = "LinkedIn"
      href = "https://www.linkedin.com/in/wangonya/"
    [[params.links.link]]
      name = "Email"
      href = "mailto:kwangonya@gmail.com"

[markup]
  [markup.highlight]
    style = "bw"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true
