baseurl = "https://wangonya.com"
languageCode = "en-us"
title = "Kinyanjui Wangonya"
theme = "hugo-rocinante"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    posts = "blog/:slug/"

[author]
  name = "Kinyanjui Wangonya"


[params]
    email = "kwangonya@gmail.com"
    about = """Software engineer - previously at [Andela](https://andela.com/), 
               now at [Jenga](https://www.jenga-agency.com/)."""


[[params.links]]
    [[params.links.link]]
      name = "Email"
      href = "mailto:kwangonya@gmail.com"
      smart_email_link = true
    [[params.links.link]]
      name = "LinkedIn"
      href = "https://www.linkedin.com/in/wangonya/"
      new_tab = true
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/wangonya"
      new_tab = true

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true
