baseurl = "https://wangonya.com"
languageCode = "en-us"
title = "Kelvin Wangonya Kinyanjui"
theme = "hugo-rocinante"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    posts = "blog/:slug/"

[author]
  name = "Kelvin Wangonya Kinyanjui"


[params]
    email = "kwangonya@gmail.com"
    about = "Software engineer."


[[params.links]]
    [[params.links.link]]
      name = "Email"
      href = "mailto:kwangonya@gmail.com"
      smart_email_link = true
    [[params.links.link]]
      name = "LinkedIn"
      href = "https://www.linkedin.com/in/wangonya/"
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/wangonya"
    [[params.links.link]]
      name = "Now"
      href = "/now"
    [[params.links.link]]
      name = "Uses"
      href = "/uses"

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true
