baseurl = "https://wangonya.com"
languageCode = "en-us"
title = "Kelvin Wangonya"
theme = "zweifel"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
pluralizeListTitles = false
enableGitInfo = true

[permalinks]
posts = "blog/:slug/"

[params]
about = "Software engineer. Mostly doing backend work with Python."
meta = "Wangonya's blog. | Software engineer. Mostly doing backend work with Python."
author = "Kelvin Wangonya"
authorTitle = "Software Engineer"
numberOfPostsInHomePage = 10

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 2

[[menus.main]]
name = 'Reading'
pageRef = '/reading'
weight = 3

[[menus.socials]]
name = "Github"
url = "https://github.com/wangonya"
weight = 1

[[menus.socials]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/wangonya/"
weight = 2

[[menus.socials]]
name = "Email"
url = "mailto:kwangonya@gmail.com"
weight = 3

[[menus.footer]]
name = 'Github'
url = "https://github.com/wangonya"
weight = 1

[[menus.footer]]
name = 'LinkedIn'
url = "https://www.linkedin.com/in/wangonya/"
weight = 2

[[menus.footer]]
name = 'Email'
url = "mailto:kwangonya@gmail.com"
weight = 3

[[menus.footer]]
name = 'RSS'
url = "/index.xml"

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[markup]
[markup.highlight]
style = "borland"
[markup.goldmark.renderer]
unsafe = true
