baseurl = "https://wangonya.com"
languageCode = "en-us"
title = "Kelvin Wangonya"
theme = "wangonya"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
pluralizeListTitles = false
enableGitInfo = true

[permalinks]
posts = "blog/:slug/"

[params]
about = "Software engineer. Mostly doing backend work with Python."
meta = "Wangonya's blog. | Software engineer. Mostly doing backend work with Python."
author = "Kelvin Wangonya"


[[params.footer]]
[[params.footer.link]]
name = "Home"
href = "/"
[[params.footer.link]]
name = "Blog"
href = "/blog"
[[params.footer.link]]
name = "Reading"
href = "/reading"
[[params.footer.link]]
name = "Links"
href = "/links"
[[params.footer.link]]
name = "Github"
href = "https://github.com/wangonya"
[[params.footer.link]]
name = "LinkedIn"
href = "https://www.linkedin.com/in/wangonya/"
[[params.footer.link]]
name = "Email"
href = "mailto:kwangonya@gmail.com"
[[params.footer.link]]
name = "RSS"
href = "/index.xml"

[markup]
[markup.highlight]
style = "github"
[markup.goldmark.renderer]
unsafe = true
