baseurl = "https://wangonya.com/"
title = "Kinyanjui Wangonya"
description = "Kinyanjui Wangonya's website and blog."
author = "Kinyanjui Wangonya"
enableRobotsTXT = true
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
googleAnalytics = "UA-145132150-1"

# https://xyproto.github.io/splash/docs/all.html
pygmentsCodefences = true
pygmentsStyle = "native"

[params]
sitename = "Kinyanjui Wangonya"
dateform = "January 2, 2006"
disableWebFonts = false

[[menu.main]]
name = "Blog"
url  = "/blog"
