baseurl = "https://wangonya.com"
languageCode = "en-us"
title = "Kelvin Wangonya"
theme = "smol"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
pluralizeListTitles = false

[permalinks]
    posts = "blog/:slug/"
    pinned = "blog/pinned/:slug/"

[params]
    email = "kwangonya@gmail.com"
    about = "Software engineer. Mostly backend work with Python."
    meta = "Wangonya's blog. | Software engineer. Mostly backend related stuff with Python."
    author = "Kelvin Wangonya"

# Header
[menu]
  [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog/"
        weight = 1

[[params.links]]
    [[params.links.link]]
      name = "Now"
      href = "/now"
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/wangonya"
    [[params.links.link]]
      name = "LinkedIn"
      href = "https://www.linkedin.com/in/wangonya/"
    [[params.links.link]]
      name = "Email"
      href = "mailto:kwangonya@gmail.com"
      smart_email_link = true

[markup]
  [markup.highlight]
    style = "algol_nu"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true
