baseurl = "https://wangonya.com"
languageCode = "en-us"
title = "Kelvin Wangonya"
theme = "wangonya"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"
pluralizeListTitles = false
enableGitInfo = true

[permalinks]
posts = "blog/:slug/"

[params]
about = "Software engineer. Mostly doing backend and data engineering work with Python."
meta = "Kelvin Wangonya's blog. | Software engineer. Mostly doing backend and data engineering work with Python."
author = "Kelvin Wangonya"
authorTitle = "Software Engineer"

[[menus.footer]]
name = 'Home'
url = "/"
weight = 1

[[menus.footer]]
name = 'Blog'
url = "/blog"
weight = 2

[[menus.footer]]
name = 'Github'
url = "https://github.com/wangonya"
weight = 3

[[menus.footer]]
name = 'LinkedIn'
url = "https://www.linkedin.com/in/wangonya/"
weight = 4

[[menus.footer]]
name = 'Email'
url = "mailto:kwangonya@gmail.com"
weight = 5

[[menus.footer]]
name = 'RSS'
url = "/index.xml"
weight = 6

[module]
[module.hugoVersion]
extended = false
min = "0.146.0"

[markup]
[markup.highlight]
style = "vs"
[markup.goldmark.renderer]
unsafe = true
