#+title: Making your SMART goals smarter with Stretch goals
#+author: Kelvin Wangonya
#+date: 2019-08-30
#+tags[]: productivity


I've been reading the book "Smarter Faster Better" by Charles Duhigg and
in it, he gives a perspective on goal-setting that I found interesting.

You may already know about
[[https://www.mindtools.com/pages/article/smart-goals.htm][SMART
goals]], which is an awesome format to set your goals in. It does have a
subtle pitfall though: cognitive closure.

*** Cognitive closure
    :PROPERTIES:
    :CUSTOM_ID: cognitive-closure
    :END:

#+begin_quote
  Cognitive closure (psychology), the human desire to eliminate
  ambiguity and arrive at definite conclusions (sometimes
  irrationally) -
  [[https://en.wikipedia.org/wiki/Cognitive_closure][Wikipedia]]
#+end_quote

You know that nice feeling of crossing things off your to-do list?
Closure. Which is great, for the most part. It only gets bad when we end
up expending more effort to get immediate results, when we are so
focused on small daily "wins" that we lose focus on the larger picture.

#+begin_quote
  “You get into this mindset where crossing things off your to-do list
  becomes more important that asking yourself if you're doing the right
  things. - The book

  "To-do lists are great if you're using them correctly. But when people
  say things like 'I sometimes write down easy items I can cross off
  right away, because it makes me feel good', that's exactly the /wrong/
  way to create a to-do list. That signals you're using it for mood
  repair, rather than to become productive." - Timothy Pychyl, quoted in
  the book
#+end_quote

I think it's easier to fall into this trap than most of us would like to
admit.

*** Combining SMART goals with Stretch goals
    :PROPERTIES:
    :CUSTOM_ID: combining-smart-goals-with-stretch-goals
    :END:
Stretch goals are goals that may be considered audacious, but
achievable. These are the kind of goals you may think about when asked
to "dream big". The point is to have one major goal that is not
immediately achievable, then use the SMART strategy to form sub-goals
that move you closer to achieving the main goal. Here's an example from
the book:

- Stretch goal: run a marathon
- Specific sub-goal: run 7 miles without stopping
- Measurable: run twice around the park, no walking
- Achievable?: yes, if I run 3 times a week
- Realistic?: yes, if I wake up early on Mondays, Wednesdays, and
  Fridays
- Timeline: run 3 miles this week, 4 miles next week, 5 miles...

Setting goals in this format ensures that we do get those small daily
wins, and always stay focused on the big picture.
